
version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPW}
      MONGO_INITDB_DATABASE: ${MONGODB}
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./create-db.sql:/create-db.sql
      - ./entrypoint.sh:/entrypoint.sh
    command:
      - /bin/bash
      - /entrypoint.sh
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    container_name: some-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITUSER}
      RABBITMQ_DEFAULT_PASS: ${RABBITPW}
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped
  dls_backend:
    build:
      context: ./dls_backend/DLS_Backend
    ports:
      - "5012:5012"
    environment:
      - ASPNETCORE_URLS=http://+:5012
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET=${JWT_SECRET}
      - RABBITUSER=${RABBITUSER}
      - RABBITPW=${RABBITPW}
      - RABBITURL=${RABBITURL}
      - DB_SERVER=${DB_INTERNAL_DOCKER_SERVER}
      - DB_BACKEND=${DB_BACKEND}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  db_changes:
    build:
      context: ./dls_dbChanges
    ports:
      - "5000:5000"  # Map the host port to the container port
    environment:
      - RABBITUSER=${RABBITUSER}
      - RABBITPW=${RABBITPW}
      - RABBITURL=${RABBITURL}
      - MONGOUSER=${MONGOUSER}
      - MONGOPW=${MONGOPW}
      - MONGOURL=${MONGOURL}
      - MONGODB=${MONGODB}
  db_user_changes:
    build:
      context: ./dls_dbUserChanges
    ports:
      - "5001:5001"  # Map the host port to the container port
    environment:
      - RABBITUSER=${RABBITUSER}
      - RABBITPW=${RABBITPW}
      - RABBITURL=${RABBITURL}
      - DB_SERVER=${DB_INTERNAL_DOCKER_SERVER}
      - DB_FRONTEND=${DB_FRONTEND}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

