# Dockerfile.nginx
FROM nginx:latest

RUN mkdir -p /usr/share/nginx/html/images
RUN mkdir -p /tmp

COPY nginx.conf /etc/nginx/nginx.conf
COPY ./cdn_images /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
