apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: auth-db
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/dls-project-default: "true"
        io.kompose.service: auth-db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: YourStrongPassword123
          image: mcr.microsoft.com/mssql/server:2019-latest
          name: auth-db
          ports:
            - containerPort: 1433
              hostPort: 1434
              protocol: TCP
      restartPolicy: Always
