apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: auth-backend
  name: auth-backend
spec:
  ports:
    - name: "5012"
      port: 5012
      targetPort: 5012
  selector:
    io.kompose.service: auth-backend
