apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: auth-db
  name: auth-db
spec:
  ports:
    - name: "1434"
      port: 1434
      targetPort: 1433
  selector:
    io.kompose.service: auth-db
