apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: auth-backend
  name: auth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/dls-project-default: "true"
        io.kompose.service: auth-backend
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:5012
            - name: DB_BACKEND
              value: usersDb
            - name: DB_PASSWORD
              value: YourStrongPassword123
            - name: DB_SERVER
              value: auth_db,1433
            - name: DB_USER
              value: SA
            - name: FRONTENDURL
              value: http://localhost:8080
            - name: JWT_SECRET
              value: MmIxM2Q1NjNmNjA1YjNiYjZiNWY0M2VjOTVhMmFhZWVmMWQ3ODAwNDlkOTFkNjJlMGQ3YzA0ZDcwZDQ2ZGU0NA==
            - name: RABBITPW
              value: password
            - name: RABBITURL
              value: rabbitmq
            - name: RABBITUSER
              value: user
          image: auth-backend
          imagePullPolicy: Never
          name: backend
          ports:
            - containerPort: 5012
              hostPort: 5012
              protocol: TCP
      restartPolicy: Always
