apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: cdn-changes
  name: cdn-changes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cdn-changes
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/dls-project-default: "true"
        io.kompose.service: cdn-changes
    spec:
      containers:
        - env:
            - name: RABBITPW
              value: password
            - name: RABBITURL
              value: rabbitmq
            - name: RABBITUSER
              value: user
          image: cdn-changes
          imagePullPolicy: IfNotPresent
          name: cdn-changes
          ports:
            - containerPort: 5020
              hostPort: 5020
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/images
              name: nginx-data
      restartPolicy: Always
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-data
