apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: cdn-changes
  name: cdn-changes
spec:
  ports:
    - name: "5020"
      port: 5020
      targetPort: 5020
  selector:
    io.kompose.service: cdn-changes
