apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: db-changes
  name: db-changes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-changes
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/dls-project-default: "true"
        io.kompose.service: db-changes
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: db-changes-config
          image: db-changes
          imagePullPolicy: Never
          name: db-changes
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
      restartPolicy: Always