apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/dls-project-default: "true"
        io.kompose.service: nginx
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "mkdir -p /usr/share/nginx/html/images"]
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-data
      restartPolicy: Always
      volumes:
        - name: nginx-data
          persistentVolumeClaim:
            claimName: nginx-data
