apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: write-api
  name: write-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: write-api
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/dls-project-default: "true"
        io.kompose.service: write-api
    spec:
      containers:
        - env:
            - name: CORS_ORIGIN
              value: http://dls-frontend:8080
            - name: DB_FRONTEND
              value: mssqlWrite
            - name: DB_PASSWORD
              value: YourStrongPassword123
            - name: DB_SERVER
              value: write_db
            - name: DB_USER
              value: SA
            - name: PORT
              value: "3000"
            - name: RABBITPW
              value: password
            - name: RABBITURL
              value: rabbitmq
            - name: RABBITUSER
              value: user
            - name: WRITE_DB_SERVER_PORT
              value: "1433"
          image: write-api
          name: write-api
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
