apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: write-db
  name: write-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: write-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose-resolved.yaml -o ./kubernetes
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/dls-project-default: "true"
        io.kompose.service: write-db
    spec:
      containers:
        - args:
            - /bin/bash
            - /entrypoint.sh
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: YourStrongPassword123
          image: mcr.microsoft.com/mssql/server:2019-latest
          name: write-db
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          volumeMounts:
            - mountPath: /create-db.sql
              name: write-db-cm0
              subPath: create-db.sql
            - mountPath: /entrypoint.sh
              name: write-db-cm1
              subPath: entrypoint.sh
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: create-db.sql
                path: create-db.sql
            name: write-db-cm0
          name: write-db-cm0
        - configMap:
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
            name: write-db-cm1
          name: write-db-cm1
